from typing import Protocol

from app.models.literature import PaperCreate, PaperRead
from app.models.material import MaterialCreate, MaterialRead
from app.models.mvp import DashboardRead, ObservationListItem, PropertyOption
from app.models.observation import ObservationCreate, ObservationRead
from app.models.search import SearchHit


class CatalogRepository(Protocol):
    async def dashboard(self) -> DashboardRead: ...

    async def list_materials(self, query: str | None, limit: int) -> list[MaterialRead]: ...

    async def get_material(self, material_id: str) -> MaterialRead | None: ...

    async def create_material(self, body: MaterialCreate) -> MaterialRead: ...

    async def list_papers(self, query: str | None, limit: int) -> list[PaperRead]: ...

    async def create_paper(self, body: PaperCreate) -> PaperRead: ...

    async def list_observations(self, limit: int) -> list[ObservationListItem]: ...

    async def create_observation(self, body: ObservationCreate) -> ObservationRead: ...

    async def list_properties(self) -> list[PropertyOption]: ...

    async def search(self, query: str, limit: int) -> list[SearchHit]: ...
